### PR TITLE
Fix out of bounds reads in ElfWriter

### LINKED ISSUE #643: Out of bounds read in ElfWriter::assembleNotes()
c7a4b44 uncovered a bug in the ElfWriter. The `memcpy` rounds up the number of bytes it copies but `note.data` contains a non-multiple of 8 number of bytes, so the `memcpy` reads more than it should.
https://github.com/GPUOpen-Drivers/llpc/blob/bb8404fa88c097b8c63cdd2fd282d8c17b8704b1/llpc/util/llpcElfWriter.cpp#L484-L486

The buffer gets allocated in `updateMetaNote`:
https://github.com/GPUOpen-Drivers/llpc/blob/bb8404fa88c097b8c63cdd2fd282d8c17b8704b1/llpc/util/llpcElfWriter.cpp#L790-L793

### PR DESCRIPTION
**Pull request by Flakebi**
This fixes #643

### CODE REVIEW

File: llpc/util/llpcElfWriter.cpp [hunk 1]
```diff
@@ -479,10 +479,14 @@ template <class Elf> void ElfWriter<Elf>::assembleNotes() {
     memcpy(data, &note.hdr, noteHeaderSize);
     data += noteHeaderSize;
     const unsigned noteNameSize = alignTo(note.hdr.nameSize, sizeof(unsigned));
-    memcpy(data, &note.hdr.name, noteNameSize);
+    memcpy(data, &note.hdr.name, note.hdr.nameSize);
+    for (unsigned i = note.hdr.nameSize; i < noteNameSize; i++)
+      data[i] = 0;
```
Comment (kuhar) [inline llpc/util/llpcElfWriter.cpp:484]: If the memcpy copies 'too little' data now, wouldn't this be solved by zero-initializing the buffer when you allocate it?

Comment (Flakebi) [reply llpc/util/llpcElfWriter.cpp:484]: Yes, that would have the same effect. I thought zeroing only the needed part is little more efficient.

Comment (amdrexu) [reply llpc/util/llpcElfWriter.cpp:484]: I think memset is more clear. If I remember correctly, PAL team once discussed this when drafting the coding style and recommended the use of memset for initialization because of its high efficiency.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 8af29b22eee85db623b5305e56f8e08536cbbb41
<details open><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master b601c88aeca7a7b08becb3d32709de383c8ee428</li>
<li>METROHASH: amd-master 2b6fee002db6cc92345b02aeee963ebaaf4c0e2f</li>
<li>PAL: dev ddcaa1009ecde219613042a5a53c6d3752bf4b9d</li>
<li>SPVGEN: dev d4817ab957f79762da83b7fc1d3f2816dbdc13fd</li>
<li>XGL: dev 2ecd2e14e2ae4f2712df4a2220e2dd36265c66d1</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 53692d985a53a336e07907c2d4b86bf2deb66908</li>
</ul></details>

<details open><summary>ShaderDB test</summary><ul>

<li>Passed: 959/959 (100.0%)</li>
<li>Failed: 0/959 (0.0%)</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix)</summary><ul>


<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 103143/103143 (100.0%)</li>
<li>Failed: 0/103143 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Navi10</summary><ul>

<li>Passed: 103199/103199 (100.0%)</li>
<li>Failed: 0/103199 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 103199/103199 (100.0%)</li>
<li>Failed: 0/103199 (0.0%)</li>
</ul></details>


</ul></details>
